services:
  longterm-api:
    build: .
    container_name: longterm-financial-api
    ports:
      - "8002:8002"
    environment:
      - ENV=production
      - LOG_LEVEL=info
    volumes:
      - "./data:/app/data:ro"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
